// Package pullRequests provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package pullRequests

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// Defines values for ErrorResponseErrorCode.
const (
	NOCANDIDATE ErrorResponseErrorCode = "NO_CANDIDATE"
	NOTASSIGNED ErrorResponseErrorCode = "NOT_ASSIGNED"
	NOTFOUND    ErrorResponseErrorCode = "NOT_FOUND"
	PREXISTS    ErrorResponseErrorCode = "PR_EXISTS"
	PRMERGED    ErrorResponseErrorCode = "PR_MERGED"
	TEAMEXISTS  ErrorResponseErrorCode = "TEAM_EXISTS"
)

// Defines values for PullRequestStatus.
const (
	MERGED PullRequestStatus = "MERGED"
	OPEN   PullRequestStatus = "OPEN"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// PullRequest defines model for PullRequest.
type PullRequest struct {
	// AssignedReviewers user_id назначенных ревьюверов (0..2)
	AssignedReviewers []string          `json:"assigned_reviewers"`
	AuthorId          string            `json:"author_id"`
	CreatedAt         *time.Time        `json:"createdAt"`
	MergedAt          *time.Time        `json:"mergedAt"`
	PullRequestId     string            `json:"pull_request_id"`
	PullRequestName   string            `json:"pull_request_name"`
	Status            PullRequestStatus `json:"status"`
}

// PullRequestStatus defines model for PullRequest.Status.
type PullRequestStatus string

// PostPullRequestCreateJSONBody defines parameters for PostPullRequestCreate.
type PostPullRequestCreateJSONBody struct {
	AuthorId        string `json:"author_id"`
	PullRequestId   string `json:"pull_request_id"`
	PullRequestName string `json:"pull_request_name"`
}

// PostPullRequestMergeJSONBody defines parameters for PostPullRequestMerge.
type PostPullRequestMergeJSONBody struct {
	PullRequestId string `json:"pull_request_id"`
}

// PostPullRequestReassignJSONBody defines parameters for PostPullRequestReassign.
type PostPullRequestReassignJSONBody struct {
	OldUserId     string `json:"old_user_id"`
	PullRequestId string `json:"pull_request_id"`
}

// PostPullRequestCreateJSONRequestBody defines body for PostPullRequestCreate for application/json ContentType.
type PostPullRequestCreateJSONRequestBody PostPullRequestCreateJSONBody

// PostPullRequestMergeJSONRequestBody defines body for PostPullRequestMerge for application/json ContentType.
type PostPullRequestMergeJSONRequestBody PostPullRequestMergeJSONBody

// PostPullRequestReassignJSONRequestBody defines body for PostPullRequestReassign for application/json ContentType.
type PostPullRequestReassignJSONRequestBody PostPullRequestReassignJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
	// (POST /pullRequest/create)
	PostPullRequestCreate(ctx echo.Context) error
	// Пометить PR как MERGED (идемпотентная операция)
	// (POST /pullRequest/merge)
	PostPullRequestMerge(ctx echo.Context) error
	// Переназначить конкретного ревьювера на другого из его команды
	// (POST /pullRequest/reassign)
	PostPullRequestReassign(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostPullRequestCreate converts echo context to params.
func (w *ServerInterfaceWrapper) PostPullRequestCreate(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPullRequestCreate(ctx)
	return err
}

// PostPullRequestMerge converts echo context to params.
func (w *ServerInterfaceWrapper) PostPullRequestMerge(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPullRequestMerge(ctx)
	return err
}

// PostPullRequestReassign converts echo context to params.
func (w *ServerInterfaceWrapper) PostPullRequestReassign(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPullRequestReassign(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/pullRequest/create", wrapper.PostPullRequestCreate)
	router.POST(baseURL+"/pullRequest/merge", wrapper.PostPullRequestMerge)
	router.POST(baseURL+"/pullRequest/reassign", wrapper.PostPullRequestReassign)

}

type PostPullRequestCreateRequestObject struct {
	Body *PostPullRequestCreateJSONRequestBody
}

type PostPullRequestCreateResponseObject interface {
	VisitPostPullRequestCreateResponse(w http.ResponseWriter) error
}

type PostPullRequestCreate201JSONResponse struct {
	Pr *PullRequest `json:"pr,omitempty"`
}

func (response PostPullRequestCreate201JSONResponse) VisitPostPullRequestCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostPullRequestCreate404JSONResponse ErrorResponse

func (response PostPullRequestCreate404JSONResponse) VisitPostPullRequestCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostPullRequestCreate409JSONResponse ErrorResponse

func (response PostPullRequestCreate409JSONResponse) VisitPostPullRequestCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostPullRequestMergeRequestObject struct {
	Body *PostPullRequestMergeJSONRequestBody
}

type PostPullRequestMergeResponseObject interface {
	VisitPostPullRequestMergeResponse(w http.ResponseWriter) error
}

type PostPullRequestMerge200JSONResponse struct {
	Pr *PullRequest `json:"pr,omitempty"`
}

func (response PostPullRequestMerge200JSONResponse) VisitPostPullRequestMergeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostPullRequestMerge404JSONResponse ErrorResponse

func (response PostPullRequestMerge404JSONResponse) VisitPostPullRequestMergeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostPullRequestReassignRequestObject struct {
	Body *PostPullRequestReassignJSONRequestBody
}

type PostPullRequestReassignResponseObject interface {
	VisitPostPullRequestReassignResponse(w http.ResponseWriter) error
}

type PostPullRequestReassign200JSONResponse struct {
	Pr PullRequest `json:"pr"`

	// ReplacedBy user_id нового ревьювера
	ReplacedBy string `json:"replaced_by"`
}

func (response PostPullRequestReassign200JSONResponse) VisitPostPullRequestReassignResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostPullRequestReassign404JSONResponse ErrorResponse

func (response PostPullRequestReassign404JSONResponse) VisitPostPullRequestReassignResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostPullRequestReassign409JSONResponse ErrorResponse

func (response PostPullRequestReassign409JSONResponse) VisitPostPullRequestReassignResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
	// (POST /pullRequest/create)
	PostPullRequestCreate(ctx context.Context, request PostPullRequestCreateRequestObject) (PostPullRequestCreateResponseObject, error)
	// Пометить PR как MERGED (идемпотентная операция)
	// (POST /pullRequest/merge)
	PostPullRequestMerge(ctx context.Context, request PostPullRequestMergeRequestObject) (PostPullRequestMergeResponseObject, error)
	// Переназначить конкретного ревьювера на другого из его команды
	// (POST /pullRequest/reassign)
	PostPullRequestReassign(ctx context.Context, request PostPullRequestReassignRequestObject) (PostPullRequestReassignResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PostPullRequestCreate operation middleware
func (sh *strictHandler) PostPullRequestCreate(ctx echo.Context) error {
	var request PostPullRequestCreateRequestObject

	var body PostPullRequestCreateJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostPullRequestCreate(ctx.Request().Context(), request.(PostPullRequestCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostPullRequestCreate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostPullRequestCreateResponseObject); ok {
		return validResponse.VisitPostPullRequestCreateResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostPullRequestMerge operation middleware
func (sh *strictHandler) PostPullRequestMerge(ctx echo.Context) error {
	var request PostPullRequestMergeRequestObject

	var body PostPullRequestMergeJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostPullRequestMerge(ctx.Request().Context(), request.(PostPullRequestMergeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostPullRequestMerge")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostPullRequestMergeResponseObject); ok {
		return validResponse.VisitPostPullRequestMergeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostPullRequestReassign operation middleware
func (sh *strictHandler) PostPullRequestReassign(ctx echo.Context) error {
	var request PostPullRequestReassignRequestObject

	var body PostPullRequestReassignJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostPullRequestReassign(ctx.Request().Context(), request.(PostPullRequestReassignRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostPullRequestReassign")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostPullRequestReassignResponseObject); ok {
		return validResponse.VisitPostPullRequestReassignResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
